package com.shiplocate.data.mapper

import com.shiplocate.core.database.entity.LoadEntity
import com.shiplocate.core.database.entity.StopEntity
import com.shiplocate.data.network.dto.load.LegDto
import com.shiplocate.data.network.dto.load.LocalizedValueDto
import com.shiplocate.data.network.dto.load.LocalizedValuesDto
import com.shiplocate.data.network.dto.load.LoadDto
import com.shiplocate.data.network.dto.load.NavigationInstructionDto
import com.shiplocate.data.network.dto.load.PolylineDto
import com.shiplocate.data.network.dto.load.RouteDto
import com.shiplocate.data.network.dto.load.RouteLatLngDto
import com.shiplocate.data.network.dto.load.StepDto
import com.shiplocate.data.network.dto.load.StopDto
import com.shiplocate.data.network.dto.load.WaypointLocationDto
import com.shiplocate.domain.model.load.Leg
import com.shiplocate.domain.model.load.Load
import com.shiplocate.domain.model.load.LoadStatus
import com.shiplocate.domain.model.load.LocalizedValue
import com.shiplocate.domain.model.load.LocalizedValues
import com.shiplocate.domain.model.load.NavigationInstruction
import com.shiplocate.domain.model.load.Polyline
import com.shiplocate.domain.model.load.Route
import com.shiplocate.domain.model.load.RouteLatLng
import com.shiplocate.domain.model.load.Step
import com.shiplocate.domain.model.load.Stop
import com.shiplocate.domain.model.load.WaypointLocation

fun LoadDto.toDomain(): Load {
    return Load(
        id = id, // Internal ID for application operations
        serverId = id, // serverId используется для API вызовов (must match server's ID)
        loadName = loadName, // Name for UI display
        description = description,
        lastUpdated = lastUpdated,
        createdAt = createdAt,
        loadStatus = loadStatus.toLoadStatus(),
        stops = stops.map { it.toDomain() },
    )
}

fun Int.toLoadStatus(): LoadStatus {
    return when (this) {
        1 -> LoadStatus.LOAD_STATUS_NOT_CONNECTED
        4 -> LoadStatus.LOAD_STATUS_CONNECTED
        5 -> LoadStatus.LOAD_STATUS_DISCONNECTED
        3 -> LoadStatus.LOAD_STATUS_REJECTED
        else -> LoadStatus.LOAD_STATUS_UNKNOWN
    }
}

fun LoadDto.toEntity(): LoadEntity {
    return LoadEntity(
        loadName = loadName, // Name for UI display
        id = id, // Internal ID for application operations
        serverId = id, // serverId используется для API вызовов (must match server's ID)
        description = description,
        lastUpdated = lastUpdated,
        createdAt = createdAt,
        loadStatus = loadStatus,
    )
}

fun LoadDto.toStopEntities(loadId: Long): List<StopEntity> {
    return stops.map { stopDto ->
        StopEntity(
            loadId = loadId,
            serverId = stopDto.id,
            type = stopDto.type,
            locationName = stopDto.locationName,
            locationAddress = stopDto.locationAddress,
            date = stopDto.date,
            geofenceRadius = stopDto.geofenceRadius,
            stopIndex = stopDto.index,
            latitude = stopDto.latitude,
            longitude = stopDto.longitude,
            enter = stopDto.enter,
            note = stopDto.note,
            completion = stopDto.completion
        )
    }
}

fun StopDto.toDomain(): Stop {
    return Stop(
        id = id,
        type = type,
        locationName = locationName,
        locationAddress = locationAddress,
        date = date,
        geofenceRadius = geofenceRadius,
        index = index,
        latitude = latitude,
        longitude = longitude,
        enter = enter,
        note = note,
        completion = completion
    )
}

fun StopDto.toStopEntity(loadId: Long): StopEntity {
    return StopEntity(
        loadId = loadId,
        serverId = id,
        type = type,
        locationName = locationName,
        locationAddress = locationAddress,
        date = date,
        geofenceRadius = geofenceRadius,
        stopIndex = index,
        latitude = latitude,
        longitude = longitude,
        enter = enter,
        note = note,
        completion = completion
    )
}

fun StopEntity.toDomain(): Stop {
    return Stop(
        id = serverId,
        type = type,
        locationName = locationName,
        locationAddress = locationAddress,
        date = date,
        geofenceRadius = geofenceRadius,
        index = stopIndex,
        latitude = latitude,
        longitude = longitude,
        enter = enter,
        note = note,
        completion = completion
    )
}

fun Stop.toEntity(loadId: Long): StopEntity {
    return StopEntity(
        id = 0, // Auto-generated by Room
        loadId = loadId,
        serverId = id,
        type = type,
        locationName = locationName,
        locationAddress = locationAddress,
        date = date,
        geofenceRadius = geofenceRadius,
        stopIndex = index,
        latitude = latitude,
        longitude = longitude,
        enter = enter,
        note = note,
        completion = completion
    )
}

fun LoadEntity.toDomain(): Load {
    return Load(
        id = id,
        serverId = serverId,
        loadName = loadName,
        description = description,
        lastUpdated = lastUpdated,
        createdAt = createdAt,
        loadStatus = loadStatus.toLoadStatus(),
        stops = emptyList(), // Stops загружаются отдельно через StopsLocalDataSource
    )
}

fun LoadStatus.toInt(): Int {
    return when (this) {
        LoadStatus.LOAD_STATUS_NOT_CONNECTED -> 1
        LoadStatus.LOAD_STATUS_CONNECTED -> 4
        LoadStatus.LOAD_STATUS_DISCONNECTED -> 5
        LoadStatus.LOAD_STATUS_REJECTED -> 3
        LoadStatus.LOAD_STATUS_UNKNOWN -> 0
    }
}

fun Load.toEntity(): LoadEntity {
    return LoadEntity(
        id = id,
        serverId = serverId,
        loadName = loadName,
        description = description,
        lastUpdated = lastUpdated,
        createdAt = createdAt,
        loadStatus = loadStatus.toInt(),
    )
}

fun RouteDto.toDomain(): Route {
    return Route(
        distanceMeters = distanceMeters,
        duration = duration,
        legs = legs?.map { it.toDomain() },
    )
}

fun LegDto.toDomain(): Leg {
    return Leg(
        distanceMeters = distanceMeters,
        duration = duration,
        polyline = polyline?.toDomain(),
        steps = steps?.map { it.toDomain() },
    )
}

fun StepDto.toDomain(): Step {
    return Step(
        distanceMeters = distanceMeters,
        staticDuration = staticDuration,
        polyline = polyline?.toDomain(),
        startLocation = startLocation?.toDomain(),
        endLocation = endLocation?.toDomain(),
        navigationInstruction = navigationInstruction?.toDomain(),
        localizedValues = localizedValues?.toDomain(),
        travelMode = travelMode,
    )
}

fun WaypointLocationDto.toDomain(): WaypointLocation {
    return WaypointLocation(
        latLng = latLng?.toDomain(),
    )
}

fun RouteLatLngDto.toDomain(): RouteLatLng {
    return RouteLatLng(
        latitude = latitude,
        longitude = longitude,
    )
}

fun PolylineDto.toDomain(): Polyline {
    return Polyline(
        encodedPolyline = encodedPolyline,
    )
}

fun NavigationInstructionDto.toDomain(): NavigationInstruction {
    return NavigationInstruction(
        maneuver = maneuver,
        instructions = instructions,
    )
}

fun LocalizedValuesDto.toDomain(): LocalizedValues {
    return LocalizedValues(
        distance = distance?.toDomain(),
        staticDuration = staticDuration?.toDomain(),
    )
}

fun LocalizedValueDto.toDomain(): LocalizedValue {
    return LocalizedValue(
        text = text,
    )
}
